coverage:
  status:
    patch:
        default:
          # basic
          target: 80%
          threshold: 10%
          base: auto 
          # advanced
          branches: 
            - master
          if_ci_failed: error #success, failure, error, ignore
          only_pulls: false
          flags: 
            - "unit"
          paths: 
            - "src"
    project:
      default:
        # basic
        target: 60% 
        threshold: 10%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced settings
        branches: 
          - master
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false