name: coverage
on: pull_request
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 18
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # Install dependencies
      - run: npm ci

      # Run tests
      - run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Exotica0122/Typefast
